// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// <define:import.meta.env>
var define_import_meta_env_default = { MODE: "production", BASE_URL: "/", DEV: false, PROD: true, SSR: false };

// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-packages.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-packages.ts
var list_packages_default = defineTool({
  name: "list_packages",
  title: "List travel packages",
  description: "List Najma Global travel packages (Umrah, Hajj, study abroad, medical, visas) with price, duration and category.",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter, e.g. 'umrah' or 'hajj'."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum packages to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("packages").select("id, slug, title, category, description, price, duration_days").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.ilike("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { packages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_bookings_default = defineTool2({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List the signed-in user's Najma Global bookings with status, travel date and service type.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bookings").select(
      "id, service_type, package_label, travel_date, travelers_count, status, amount, contact_email, notes, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-booking.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_booking_default = defineTool3({
  name: "create_booking",
  title: "Create a booking",
  description: "Create a Najma Global booking request for the signed-in user. The booking starts in 'pending' status until the team confirms it.",
  inputSchema: {
    service_type: z2.string().describe("Service: umrah, hajj, study-abroad, medical-tourism or travel-visas."),
    package_label: z2.string().optional().describe("Package or tier name, if known."),
    travel_date: z2.string().optional().describe("Preferred travel date as YYYY-MM-DD."),
    travelers_count: z2.number().int().min(1).max(50).optional().describe("Number of travellers (default 1)."),
    contact_name: z2.string().describe("Full name of the primary contact."),
    contact_email: z2.string().describe("Contact email address."),
    contact_phone: z2.string().describe("Contact phone number."),
    notes: z2.string().optional().describe("Extra requests or context.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bookings").insert({
      user_id: ctx.getUserId(),
      service_type: input.service_type,
      package_label: input.package_label ?? null,
      travel_date: input.travel_date ?? null,
      travelers_count: input.travelers_count ?? 1,
      contact_name: input.contact_name,
      contact_email: input.contact_email,
      contact_phone: input.contact_phone,
      notes: input.notes ?? null,
      status: "pending"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/submit-inquiry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_inquiry_default = defineTool4({
  name: "submit_inquiry",
  title: "Submit a contact inquiry",
  description: "Send a contact inquiry to the Najma Global team on behalf of the signed-in user.",
  inputSchema: {
    name: z3.string().describe("Name of the person making the inquiry."),
    email: z3.string().describe("Reply-to email address."),
    subject: z3.string().optional().describe("Short subject line."),
    message: z3.string().describe("The inquiry message.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("contact_inquiries").insert({
      name: input.name,
      email: input.email,
      subject: input.subject ?? null,
      message: input.message,
      source: "mcp"
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Inquiry submitted. The Najma Global team will follow up by email." }],
      structuredContent: { submitted: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = define_import_meta_env_default.VITE_SUPABASE_PROJECT_ID ?? "chhtzqpyvheuklyrsmjj";
var mcp_default = defineMcp({
  name: "najma-global-journey",
  title: "Najma Global Journey",
  version: "0.1.0",
  instructions: "Tools for Najma Global Tours & Consulting. Use `list_packages` to browse Umrah, Hajj, study abroad, medical tourism and visa packages; `list_my_bookings` to read the signed-in user's bookings; `create_booking` to request a new booking; and `submit_inquiry` to contact the team.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_packages_default, list_my_bookings_default, create_booking_default, submit_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
